name: "pr-checks-2"

on: [push]

jobs:
  lint-python:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install poetry==1.1.13
          pip install pre-commit==2.13.0
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi

      - name: Run pre-commit on all files
        run: |
          pre-commit run --all-files

  test-python:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./math_api

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install poetry==1.1.13
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi

      - name: Unit tests + Coverage report
        run: |
          pytest --cov=./ --cov-report=xml

      - name: Upload coverage
        uses: codecov/codecov-action@v1
